version: "3"

services:
    pswdgen:
        container_name: pswdgen
        build: ./pswdgen
        entrypoint: java -Xmx256m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8181,suspend=n -jar /app.jar

    mproximate:
        container_name: mproximate
        build: ./mproximate
        entrypoint: java -Xmx256m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8181,suspend=n -jar /app.jar
